---
version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/buildpack-deps:focal

commands:
  registry_login:
    description: Login Container Registry
    steps:
      - run:
          name: Login Container Registry
          command: |
            echo "${CONTAINER_REGISTRY_PASS}" | docker login --username ${CONTAINER_REGISTRY_LOGIN} --password-stdin docker.io

  build:
    description: Build Container OCI
    parameters:
      workdir:
        default: "~/project"
        type: string
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - registry_login
      - run:
          name: Build Container OCI
          command: |
            pwd
            cd << parameters.workdir >>
            ../../.circleci/build.sh
      - store_artifacts:
          path: << parameters.workdir >>/images/image.oci

jobs:
  shellcheck:
    docker:
      - image: koalaman/shellcheck-alpine:v0.7.1
    steps:
      - checkout
      - run:
          name: Shellcheck Scripts
          command: |
            find . -type f -name '*.sh' | wc -l
            find . -type f -name '*.sh' | xargs shellcheck --external-sources -e SC2129,SC2001,SC2013

  ###
  ## OS base images
  #
  alpine:
    executor: docker-executor
    steps:
      - build:
          workdir: "./projects/alpine"

  centos:
    executor: docker-executor
    steps:
      - build:
          workdir: "./projects/centos"

  ubuntu:
    executor: docker-executor
    steps:
      - build:
          workdir: "./projects/ubuntu"

  ###
  ## Development and Runtimes
  #
  openjdk-jdk-11:
    executor: docker-executor
    steps:
      - build:
          workdir: "./projects/openjdk-jdk-11"

  openjdk-jre-11:
    executor: docker-executor
    steps:
      - build:
          workdir: "./projects/openjdk-jre-11"

  maven:
    executor: docker-executor
    steps:
      - build:
          workdir: "./projects/maven"

  ###
  ## Web Tools
  #
  hastebin:
    executor: docker-executor
    steps:
      - build:
          workdir: "./projects/hastebin"

  ###
  ## Infrastructure
  #
  activemq:
    executor: docker-executor
    steps:
      - build:
          workdir: "./projects/activemq"

  freeradius:
    executor: docker-executor
    steps:
      - build:
          workdir: "./projects/freeradius"

  gobgp:
    executor: docker-executor
    steps:
      - build:
          workdir: "./projects/gobgp"

  isc-dhcp:
    executor: docker-executor
    steps:
      - build:
          workdir: "./projects/isc-dhcp"

  mini-mail:
    executor: docker-executor
    steps:
      - build:
          workdir: "./projects/mini-mail"

  murmur:
    executor: docker-executor
    steps:
      - build:
          workdir: "./projects/murmur"

  net-snmp:
    executor: docker-executor
    steps:
      - build:
          workdir: "./projects/net-snmp"


workflows:
  commit:
    jobs:
      - shellcheck
      - alpine:
          context: 
            - dockerhub
          requires:
            - shellcheck
      - centos:
          context: 
            - dockerhub
          requires:
            - shellcheck
      - ubuntu:
          context: 
            - dockerhub
          requires:
            - shellcheck
      - openjdk-jdk-11:
          context: 
            - dockerhub
          requires:
            - ubuntu
      - openjdk-jre-11:
          context: 
            - dockerhub
          requires:
            - ubuntu
      - maven:
          context: 
            - dockerhub
          requires:
            - openjdk-jdk-11
      - hastebin:
          context: 
            - dockerhub
          requires:
            - shellcheck
      - activemq:
          context: 
            - dockerhub
          requires:
            - centos
      - freeradius:
          context: 
            - dockerhub
          requires:
            - shellcheck
      - gobgp:
          context: 
            - dockerhub
          requires:
            - ubuntu
      - isc-dhcp:
          context: 
            - dockerhub
          requires:
            - shellcheck
      - mini-mail:
          context: 
            - dockerhub
          requires:
            - ubuntu
      - murmur:
          context: 
            - dockerhub
          requires:
            - shellcheck
      - net-snmp:
          context: 
            - dockerhub
          requires:
            - shellcheck
