version: 2.0

defaults: &defaults

aliases:
  - &docker_environment
    - image: docker:18.06.0-ce-git
  - &checkout
    path: ~/opennms-container
  - &build_container
    name: Building Container Image
    command: ~/opennms-container/.circleci/build.sh
  - &registry_login
    name: Login Container Registry
    command: docker login -u ${CONTAINER_REGISTRY_LOGIN} -p ${CONTAINER_REGISTRY_PASS}
  - &common_steps
    - checkout: *checkout
    - setup_remote_docker
    - run: apk add --no-cache bash
    - run: *registry_login
    - run: *build_container
    - store_artifacts:
        path: images/image.oci
  - &common_environment
    docker: *docker_environment
    steps: *common_steps

jobs:
  shellcheck:
    docker:
      - image: no42org/shellcheck:0.5.0
    steps:
      - checkout
      - run:
          name: Shellcheck Scripts
          command: |
            find . -type f -name '*.sh' | wc -l
            find . -type f -name '*.sh' | xargs shellcheck --external-sources -e SC2129,SC2001,SC2013
  horizon:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/horizon

  minion:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/minion

workflows:
  version: 2
  container_build_:
    jobs:
      - shellcheck
      - horizon:
          requires:
            - shellcheck
      - minion:
          requires:
            - shellcheck
