---
version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/buildpack-deps:focal

commands:
  registry_login:
    description: Login Container Registry
    steps:
      - run:
          name: Login Container Registry
          command: |
            echo "${CONTAINER_REGISTRY_PASS}" | docker login --username ${CONTAINER_REGISTRY_LOGIN} --password-stdin

  build:
    description: Build Container OCI
    parameters:
      workdir:
        default: "~/project"
        type: string
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - registry_login
      - run:
          name: Build Container OCI
          command: |
            pwd
            cd << parameters.workdir >>
            ../../.circleci/build.sh
      - store_artifacts:
          path: images/image.oci

jobs:
  shellcheck:
    docker:
      - image: koalaman/shellcheck-alpine:v0.7.1
    steps:
      - checkout
      - run:
          name: Shellcheck Scripts
          command: |
            find . -type f -name '*.sh' | wc -l
            find . -type f -name '*.sh' | xargs shellcheck --external-sources -e SC2129,SC2001,SC2013

  hastebin:
    executor: docker-executor
    steps:
      - build:
          workdir: "./projects/hastebin"

  freeradius:
    executor: docker-executor
    steps:
      - build:
          workdir: "./projects/freeradius"

  murmur:
    executor: docker-executor
    steps:
      - build:
          workdir: "./projects/murmur"

  minecraft-rcon:
    executor: docker-executor
    steps:
      - build:
          workdir: "./projects/minecraft-rcon"

  minecraft-overviewer:
    executor: docker-executor
    steps:
      - build:
          workdir: "./projects/minecraft-overviewer"

  bzflag-server:
    executor: docker-executor
    steps:
      - build:
          workdir: "./projects/bzflag-server"

  onms-ovlsync:
    executor: docker-executor
    steps:
      - build:
          workdir: "./projects/onms-ovlsync"

workflows:
  commit:
    jobs:
      - shellcheck
      - hastebin:
          requires:
            - shellcheck
      - freeradius:
          requires:
            - shellcheck
      - murmur:
          requires:
            - shellcheck
      - minecraft-rcon:
          requires:
            - shellcheck
      - minecraft-overviewer:
          requires:
            - shellcheck
      - bzflag-server:
          requires:
            - shellcheck
      - onms-ovlsync:
          requires:
            - shellcheck
