version: 2.0

defaults: &defaults

aliases:
  - &docker_environment
    - image: docker:18.06.0-ce-git
  - &checkout
    path: ~/opennms-container
  - &build_container
    name: Building Container Image
    command: ~/opennms-container/.circleci/build.sh
  - &registry_login
    name: Login Container Registry
    command: docker login -u ${CONTAINER_REGISTRY_LOGIN} -p ${CONTAINER_REGISTRY_PASS}
  - &common_steps
    - checkout: *checkout
    - setup_remote_docker
    - run: apk add --no-cache bash
    - run: *registry_login
    - run: *build_container
    - store_artifacts:
        path: images/image.oci
  - &common_environment
    docker: *docker_environment
    steps: *common_steps

jobs:
  shellcheck:
    docker:
      - image: no42org/shellcheck:0.5.0
    steps:
      - checkout
      - run:
          name: Shellcheck Scripts
          command: |
            find . -type f -name '*.sh' | wc -l
            find . -type f -name '*.sh' | xargs shellcheck --external-sources -e SC2129,SC2001,SC2013

  centos:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/centos

  shairport-sync:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/shairport-sync

  net-snmp:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/net-snmp

  openjdk:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/openjdk

  oraclejdk:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/oraclejdk

  maven:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/maven

  tomcat:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/tomcat

  horizon:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/horizon

  minion:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/minion

  sentinel:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/sentinel

workflows:
  version: 2
  container_build_:
    jobs:
      - shellcheck
      - shairport-sync:
          requires:
            - shellcheck
      - tomcat:
          requires:
            - shellcheck
      - centos:
          requires:
            - shellcheck
      - net-snmp:
          requires:
            - shellcheck
      - openjdk:
          requires:
            - shellcheck
            - centos
      - oraclejdk:
          requires:
            - shellcheck
            - centos
      - maven:
          requires:
            - shellcheck
            - oraclejdk
      - horizon:
          requires:
            - shellcheck
            - centos
            - oraclejdk
      - minion:
          requires:
            - shellcheck
            - centos
            - oraclejdk
      - sentinel:
          requires:
            - shellcheck
            - centos
            - oraclejdk
