[template]
src = "collectd.properties.tpl"
dest = "/tmp/collectd.properties"
keys = [
    "/threshd/value/decimalformat",
    "/datacollectionconfig/reloadcheckinterval",
    "/collectd/instrumentationclass",
    "/collectd/snmpcollector/forcerescan",
    "/collectd/snmpcollector/limitcollectiontoinstances"
]
