[template]
src = "grafana-box.properties.tpl"
dest = "/tmp/grafana-box.properties"
keys = [
    "/grafanabox/show",
    "/grafanabox/hostname",
    "/grafanabox/port",
    "/grafanabox/basepath",
    "/grafanabox/apikey",
    "/grafanabox/tag",
    "/grafanabox/protocol",
    "/grafanabox/connectiontimeout",
    "/grafanabox/dashboardlimit"
]
