[template]
src = "opennms-datasources.xml.tpl"
dest = "/tmp/opennms-datasources.xml"
keys = [
    "/provisiond/enablediscovery",
    "/provisiond/schedulerescanforexistingnodes",
    "/provisiond/schedulerescanforupdatednodes",
    "/provisiond/repositoryimplementation",
    "/provisiond/resolvemissingcoordinatesfromaddressstring",
    "/requisition/dir",
    "/importer/foreign-source/dir",
    "/minion/provisioning",
    "/minion/provisioning/foreignsourcepattern",
    "/provision/maxconcurrentconnections",
    "/importer/adapter/dns/server",
    "/importer/adapter/dns/level",
    "/importer/adapter/dns/reverse/level"
]
