[template]
src = "timeseries.properties.tpl"
dest = "/tmp/timeseries.properties"
keys = [
    "/rrd/storebyforeignsource",
    "/rrd/storebygroup",
    "/timeseries/strategy",
    "/rrd/binary",
    "/rrd/base/dir",
    "/evaluate/dump_stats",
    "/evaluate/dump_cache",
    "/newts/nan_on_counter_wrap",
    "/newts/config/hostname",
    "/newts/config/keyspace",
    "/newts/config/port",
    "/newts/config/username",
    "/newts/config/password",
    "/newts/config/read_consistency",
    "/newts/config/write_consistency",
    "/newts/config/max_batch_size",
    "/newts/config/ring_buffer_size",
    "/newts/config/ttl",
    "/newts/config/resource_shard",
    "/newts/config/cache/strategy",
    "/newts/config/cache/max_entries",
    "/newts/query/minimum_step",
    "/newts/config/cache/redis_hostname",
    "/newts/config/cache/redis_port",
    "/newts/config/cache/priming/disable"
]
