ARG VERSION="7.5.1804"
ARG CENTOS_BASE_IMAGE=centos:"${VERSION}"

FROM ${CENTOS_BASE_IMAGE}

ARG BUILD_DATE="1970-01-01T00:00:00"

LABEL maintainer "Ronny Trommer <ronny@opennms.org>" \
      license="AGPLv3" \
      name="CentOS" \
      version="${VERSION}" \
      build.date="${BUILD_DATE}" \
      vendor="OpenNMS Community"
